### ISSUE TITLE
Feature Request: windows support

### ISSUE THREAD

**Issue by aslmx** [gh2o/rvi_capture#3]
Hi!

First: thank you sooo much for providing this tool. I love it and It works great on my linux laptop and it has made my life so much easier!

I'd really appreciate though, if i could also have my colleagues that (have to) run windows machines to benefit form this.

I only have a quite basic understanding of python. In the first lines you check for the availability of libimobiledevice.so.X
That looks like a linux library. 

There is libimobiledevice for windows (altough i still struggle to find out how to properly install it), so it could work on windows as well.

Would it be possible for you - without spending too much effort - to make your python code support windows?

That'd be awesome!

Thanks for considering!

**Comment by gh2o** [comment]
It's been added!

**Comment by aslmx** [comment]
Thanks a lot already!

Is there a way getting this running WITHOUT Itunes? I mean... it runs without Itunes on Linux too...

thx

**Comment by gh2o** [comment]
The script requires iTunes on Windows because it communicates with your iPhone through `AppleMobileDeviceService.exe` and its associated device drivers. On Linux, `usbmuxd` provides the the same role and is usually automatically installed along with libimobiledevice.

You could try this Windows build of usbmuxd, and tell me if it works: https://dev.azure.com/libimobiledevice-win32/af904318-d97c-4bf6-bf5a-f8249ec16c25/_apis/build/builds/400/artifacts?artifactName=usbmuxd&api-version=5.2-preview.5&%24format=zip

**Comment by aslmx** [comment]
Hi,

thanks for the link. I couldn't get usbmuxd.exe running. I tried for some hours but eventually i can successfully rn rvi_capture on Windows. 

My steps
1. install python3 for windows (add to PATH!)
2. clone rvi_capture (sure... ;))
3. install 7zip if not yet install
4. download Itunes Installer.msi from Apple
5. Extract
    AppleApplicationSupport64.msi  and
    AppleMobileDeviceSupport64.msi
   from Itunes installer.msi
6. Install the two msi files, ApplicationSupport first, otherwise you cant install DeviceSupport!
7. optionally reboot

rvi_capture works....

So... you do not have to install Itunes, but half of it ;) One can decide for oneselve if thats better than install full itunes, but... yeah.
Maybe you can add a note about this into readme.md for fellow windows users?
(of course usbmuxd.exe  or idevice_id.exe from libimobiledevice now also work. I guess it has the same dependency on the itunes stuff...)

Thanks a lot anyway for adding windows support to the Python script :-)

**Comment by wes1993** [comment]
Hello, i'm trying to run this in windows but i have this errors... what is the correct command for run in windows with wireshark?
```
PS C:\Users\stefa\Desktop> python rvi_capture.py - | wireshark -k -i -
wireshark : Termine 'wireshark' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script.
Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:27
+ python rvi_capture.py - | wireshark -k -i -
+                           ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (wireshark:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\stefa\Desktop> ./rvi_capture.py - | wireshark -k -i -
./rvi_capture.py : Termine './rvi_capture.py' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o
file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ ./rvi_capture.py - | wireshark -k -i -
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./rvi_capture.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : `CommandNotFoundException
```

Thanks a lot
Stefano

**Comment by gh2o** [comment]
> Hello, i'm trying to run this in windows but i have this errors... what is the correct command for run in windows with wireshark?

You need to replace `wireshark` with the full path to `wireshark.exe`
