### ISSUE TITLE
analog of rvi_capture for non-root Android

### ISSUE THREAD

**Issue by viralpump** [gh2o/rvi_capture#5]
Hey. Your work on the rvi_capture is wonderful.
But I have a question. Is it possible to write a similar tool for non-root android?
I know about tcpdump, but it's different. 
I don’t want to install anything on a android device, as in the case of a tcpdump.
And it is important that this tool works with android without root, as your tool does. After all, for his work on the iPhone does not need a jailbreak.
What do you think, is it real?

**Comment by daluu** [comment]
With exception of installing app on Android device, there's: https://play.google.com/store/apps/details?id=jp.co.taosoftware.android.packetcapture&hl=en

**Comment by gh2o** [comment]
Rooting is probably required on Android. This is out of scope for this project.
