### ISSUE TITLE
rvi_capture Error : __main__.IDeviceError: Error in libimobiledevice: Missing Error

### ISSUE THREAD

**Issue by oi23mkoshiba** [gh2o/rvi_capture#6]
I wrote from Japan, so I apologized for my poor English.

I get this bug.
This packet capture utility says "Error Missing".
```
Traceback (most recent call last):
    File "./rvi_capture.py", line 366, in <module>
        main()
    File "./rvi_capture.py", line 356, in main
        packet_dumper.run(packet_callback)
    File "./rvi_capture.py", line 295, in run
        for pkt in self.pkt_iter:
    File "./rvi_capture.py", line 183, in __iter__
        [chunk_len] = UB32.unpack(read_fully(4))
    File "./rvi_capture.py", line 178, in read_fully
        b += conn.recv(n - l)
    File "./rvi_capture.py", line 123, in recv
        self.handle, out, num_bytes, ctypes.byref(out_bytes), ctypes.c_uint(599)))
    File "./rvi_capture.py", line 59, in check
        raise cls(err)
__main__.IDeviceError: Error in libimobiledevice: Missing Error
```
So, I try to see the error code, and the error code is -7.
Source is written:
```
error = 'Error in libimobiledevice: ' + {
    0: 'Success',
    -1: 'Invalid Argument',
    -2: 'Unknown Error',
    -3: 'No Device',
    -4: 'Not Enough Data',
    -5: 'Bad Header',
    -6: 'SSL Error',
}.get(code, 'Missing Error')
```
But I get the error code, -7.
I can't solve this bug. Any ideas?

On Fedora 31 with a device running iOS 12.4.5
thanks

**Comment by lnguy1933** [comment]
I have the same error. Did you manage it? Thanks

**Comment by Jimbolino** [comment]
I've had the same problem.
Solved it by disabling the error handler:

on line 60: change `raise cls(err)` into `pass`

With this I was able to capture the packets needed to extract the user/pass from a pop3 account.
Much easier than setting up a man in the middle router with packet capture. (since mail on ios does not use the http proxy)

**Comment by gh2o** [comment]
Should be solved with recent commits, re-open this issue if not.
