### ISSUE TITLE
Sorry, not an issue but a question. 

### ISSUE THREAD

**Issue by SuperKenVery** [gh2o/rvi_capture#8]
Sorry for contacting you in such an abrupt way, but it seems that there’s no other way to contact you. 
But could you please teach me 
#### **how to obtain the string “ com.apple.pcapd”**
? 

After reading your code, I found that the core of it is connecting to an on device service called com.apple.pcapd  But, if I were to develop this thing myself, I would have no way to obtain this name. I tried packet capturing on USB port using wire shark, but it soon went into SSL and I can no longer know what’s happening, leave alone the service’s name and format. 

So could you please tell me how to get the service name “com.apple.pcapd”? Thanks a lot! Again sorry for contacting you in such a way.

**Comment by gh2o** [comment]
I'm pretty sure I found it somewhere on the Internet.

**Comment by SuperKenVery** [comment]
Thanks a lot! I guess I will have to figure that out myself. 

To be honest, what I want to do is wired network sharing for iOS devices. This can be easily done on macOS by selecting iPad usb (or iPhone usb) in network in sharing, but cannot be done on Linux or windows. Thank you anyway!
